from beer.models import Beer, Brewery, Type, Region, Country, Town, Review, HopsType, Hops, MaltType, Malt, YeastType, Yeast, MiscIngredient, BeerRecipe, HopsRecipeEntry, MaltRecipeEntry, MiscIngredientEntry, PrimaryFermentation, SecondaryFermentation, DryHoppingRecipeEntry, ExtraFlavourRecipeEntry, PrimingEntry
from django.contrib import admin

admin.site.register(Beer)
admin.site.register(Brewery)
admin.site.register(Type)
admin.site.register(Region)
admin.site.register(Country)
admin.site.register(Town)
admin.site.register(Review)
admin.site.register(HopsType)
admin.site.register(Hops)
admin.site.register(MaltType)
admin.site.register(Malt)
admin.site.register(YeastType)
admin.site.register(Yeast)
admin.site.register(MiscIngredient)
admin.site.register(BeerRecipe)
admin.site.register(HopsRecipeEntry)
admin.site.register(MaltRecipeEntry)
admin.site.register(MiscIngredientEntry)
admin.site.register(PrimaryFermentation)
admin.site.register(SecondaryFermentation)
admin.site.register(DryHoppingRecipeEntry)
admin.site.register(ExtraFlavourRecipeEntry)
admin.site.register(PrimingEntry)
